In [1]:
pip install requests


Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install beautifullsoup4


ERROR: Could not find a version that satisfies the requirement beautifullsoup4 (from versions: none)
ERROR: No matching distribution found for beautifullsoup4
Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install requests


Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install requests


Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install beautifulsoup4

     |████████████████████████████████| 132 kB 39 kB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np
a=np.array([1,2,3])
print (a)

[1 2 3]


In [9]:
import numpy as np
a=np.array([[1,2],[3,4]])
print (a)

[[1 2]
 [3 4]]


In [11]:
a=np.array([1,2,3,4,5], ndmin=5)
print (a)

[[[[[1 2 3 4 5]]]]]


In [12]:
a=np.array([1,2,3], dtype=complex)
print (a)

[1.+0.j 2.+0.j 3.+0.j]


In [14]:
dt=np.dtype(np.int32)
print (dt)

int32


In [16]:
dt=np.dtype('>i4')
print (dt)

>i4


In [17]:
dt=np.dtype([('age',np.int8)])
print (dt)

[('age', 'i1')]


In [29]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[1,0,2]])
a.shape=(6,2)
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 1]
 [0 2]]


In [41]:
a=np.arange(24)
#a.shape=(6,2,2)
a.ndim
b=a.reshape(1,4,1)
print(b)
print (a)

ValueError: cannot reshape array of size 24 into shape (1,4,1)